# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js Add department client

on:
  workflow_dispatch:
    inputs:
      TABLE_SUBABASE_NAME:
        description: "Nhập tên bảng lưu client phòng ban trên supabase:"
        required: true
        type: string

      ID_DEPARTMENT:
        description: "Nhập id phòng ban:"
        required: true
        type: string

      LARK_APP_ID:
        description: "Nhập lark app id tương ứng phòng ban:"
        required: true
        type: string

      LARK_APP_SECRET:
        description: "Nhập lark app secret tương ứng phòng ban:"
        required: true
        type: string

      STATUS:
        description: "Nhập trạng thái phòng ban (true/false):"
        required: true
        type: string


jobs:
  sync-job:
    runs-on: ubuntu-latest
    environment: sync-attendance

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci --only=production

      - name: Run add-department-supabase.js
        env:
          DATABASE_SERVICE_KEY: ${{ secrets.DATABASE_SERVICE_KEY }}
          AES_256_CBC_APP_SECRET_KEY: ${{ secrets.AES_256_CBC_APP_SECRET_KEY }}
          TABLE_SUBABASE_NAME: ${{ inputs.TABLE_SUBABASE_NAME }}
          ID_DEPARTMENT: ${{ inputs.ID_DEPARTMENT }}
          LARK_APP_ID: ${{ inputs.LARK_APP_ID }}
          LARK_APP_SECRET: ${{ inputs.LARK_APP_SECRET }}
          STATUS: ${{ inputs.STATUS }}

        run: node add-department-supabase.js
