# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Nodejs sync attendance

on:
  schedule:
    - cron: "30 16 */2 * *"
  workflow_dispatch:
    inputs:
      TABLE_NAME_ATTENDANCE:
        description: "Tên bảng cần kiểm tra"
        required: true
        type: string
        
      FROM:
        description: "Từ ngày (YYYY/MM/DD)"
        required: true
        type: string

      TO:
        description: "Đến ngày (YYYY/MM/DD)"
        required: true
        type: string

jobs:
  sync-attendance-job:
    runs-on: ubuntu-latest
    environment: sync-attendance

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci --only=production

      - name: Run sync-attendance.js
        env:
          DATABASE_SERVICE_KEY: ${{ secrets.DATABASE_SERVICE_KEY }}
          AES_256_CBC_APP_SECRET_KEY: ${{ secrets.AES_256_CBC_APP_SECRET_KEY }}
          LARK_HRM_APP_ID: ${{ secrets.LARK_HRM_APP_ID }}
          LARK_HRM_APP_SECRET: ${{ secrets.LARK_HRM_APP_SECRET }}
          LARK_BASE_ID: ${{ vars.LARK_BASE_ID }}
          TABLE_NAME_ATTENDANCE: ${{ inputs.TABLE_NAME_ATTENDANCE != '' && inputs.TABLE_NAME_ATTENDANCE || vars.TABLE_NAME_ATTENDANCE }}
          FROM: ${{ inputs.FROM != '' && inputs.FROM || vars.FROM }}
          TO: ${{ inputs.TO != '' && inputs.TO || vars.TO }}

        run: node sync-attendance.js
